# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e8dd51a8f42ad427a23efe7459f46574169fb8427fe5bbaaf114c286b2341bc5b962b5473c56f4a6b369357b71188bb8667d138c4ff466d1a828956b157cbe0

test:
  secret_key_base: fa8e58098c4b02c0c4b822026ae2d7fbfe59e5824ba5ac93287f702d8dd063e16cc112efcc97660724260e8746cd1314db101641c3bfeba257c5e914d13a2964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
